name: Global Terraform Deployment

on:
  #push:
  #branches:
  #- main
  #paths:
  #- 'terraform/global/**' # Trigger only on changes within the 'global' root directory
  workflow_dispatch: # Allows manual triggering from GitHub UI

permissions: # Apply least-privilege permissions at the workflow level
  contents: read # Required to checkout the code
  id-token: write # Required for aws-actions/configure-aws-credentials with OIDC

jobs:
  deploy_global:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1 # Ensure this matches your global/main.tf required_version

      - name: Configure AWS credentials (Global)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1 # The region where your global state bucket is located and where IAM operations are typically performed

      - name: Terraform Init (Global)
        # All subsequent Terraform commands will run from this working directory
        run: terraform init -reconfigure
        working-directory: terraform/global

      - name: Terraform Validate (Global)
        run: terraform validate
        working-directory: terraform/global

      - name: Run TFLint (Global)
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.50.0 # Match your desired TFLint version
      - run: tflint --recursive --format compact
        working-directory: terraform/global

      #- name: Run TFSEC Scan (Global)
      #uses: aquasecurity/tfsec-action@v1.0.6 # Use the working version you found
      #with:
      #working_directory: terraform/global

      #- name: Run Checkov Scan (Global)
      #uses: bridgecrewio/checkov-action@v1
      #with:
      #directory: terraform/global
      #framework: terraform

      - name: Terraform Plan (Global)
        run: |
          terraform plan -no-color \
            -var="example_api_key_value=${{ secrets.MY_SERVICE_API_KEY }}"
        working-directory: terraform/global

      - name: Terraform Apply (Global)
        run: |
          terraform apply -auto-approve \
            -var="example_api_key_value=${{ secrets.MY_SERVICE_API_KEY }}"
        working-directory: terraform/global
